"""message

Revision ID: 3aea39d7b641
Revises: fea6e15acd3b
Create Date: 2023-09-09 15:41:21.750134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aea39d7b641'
down_revision = 'fea6e15acd3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('months_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month_guarantee_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('month_guarantee_hours_worked_rated', sa.Float(), nullable=True))
        batch_op.drop_column('guarantee_hours')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('months_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guarantee_hours', sa.FLOAT(), nullable=True))
        batch_op.drop_column('month_guarantee_hours_worked_rated')
        batch_op.drop_column('month_guarantee_hours')

    # ### end Alembic commands ###
