"""message

Revision ID: 4d4c17845eb1
Revises: 8c57516791a7
Create Date: 2023-09-12 02:04:36.368684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4c17845eb1'
down_revision = '8c57516791a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('months_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month_reserve_no_fly_hours', sa.Float(), nullable=True))

    with op.batch_alter_table('pairings_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pairing_reserve_no_fly_hours', sa.Float(), nullable=True))

    with op.batch_alter_table('years_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_reserve_no_fly_hours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('years_table', schema=None) as batch_op:
        batch_op.drop_column('year_reserve_no_fly_hours')

    with op.batch_alter_table('pairings_table', schema=None) as batch_op:
        batch_op.drop_column('pairing_reserve_no_fly_hours')

    with op.batch_alter_table('months_table', schema=None) as batch_op:
        batch_op.drop_column('month_reserve_no_fly_hours')

    # ### end Alembic commands ###
