"""message

Revision ID: 4e1e8c121225
Revises: e860f7f36c7a
Create Date: 2023-09-12 02:19:22.884314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1e8c121225'
down_revision = 'e860f7f36c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('months_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month_reserve_no_fly_pay', sa.Float(), nullable=True))

    with op.batch_alter_table('pairings_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pairing_reserve_no_fly_pay', sa.Float(), nullable=True))

    with op.batch_alter_table('years_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_reserve_no_fly_pay', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('years_table', schema=None) as batch_op:
        batch_op.drop_column('year_reserve_no_fly_pay')

    with op.batch_alter_table('pairings_table', schema=None) as batch_op:
        batch_op.drop_column('pairing_reserve_no_fly_pay')

    with op.batch_alter_table('months_table', schema=None) as batch_op:
        batch_op.drop_column('month_reserve_no_fly_pay')

    # ### end Alembic commands ###
