"""message

Revision ID: 4e50c8af5bfc
Revises: 33a3a8efdd76
Create Date: 2023-09-09 10:01:02.251742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e50c8af5bfc'
down_revision = '33a3a8efdd76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pairings_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pairing_guarantee_hours_worked', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pairings_table', schema=None) as batch_op:
        batch_op.drop_column('pairing_guarantee_hours_worked')

    # ### end Alembic commands ###
