"""message

Revision ID: 52cfff0f2525
Revises: b2b6dfb59398
Create Date: 2023-09-08 13:47:19.418287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cfff0f2525'
down_revision = 'b2b6dfb59398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pairings_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pairing_guarantee_hours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pairings_table', schema=None) as batch_op:
        batch_op.drop_column('pairing_guarantee_hours')

    # ### end Alembic commands ###
