"""message

Revision ID: 7cf90bf59e28
Revises: cf219d1322ed
Create Date: 2023-09-07 15:48:50.877411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf90bf59e28'
down_revision = 'cf219d1322ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_tfp_pay', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days_table', schema=None) as batch_op:
        batch_op.drop_column('total_tfp_pay')

    # ### end Alembic commands ###
