"""message

Revision ID: 804720ade328
Revises: 3aea39d7b641
Create Date: 2023-09-10 13:11:46.269330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804720ade328'
down_revision = '3aea39d7b641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('months_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month_tafb_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('month_int_tafb_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('month_tfp_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('month_vacation_sick_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('month_vja_rated', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('month_vja_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('month_holiday_rated', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('month_holiday_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('month_time_half_rated', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('month_time_half_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('month_double_time_rated', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('month_double_time_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('month_double_half_rated', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('month_double_half_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('month_triple_rated', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('month_triple_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('month_overrides_pay', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('month_a_pay', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('months_table', schema=None) as batch_op:
        batch_op.drop_column('month_a_pay')
        batch_op.drop_column('month_overrides_pay')
        batch_op.drop_column('month_triple_pay')
        batch_op.drop_column('month_triple_rated')
        batch_op.drop_column('month_double_half_pay')
        batch_op.drop_column('month_double_half_rated')
        batch_op.drop_column('month_double_time_pay')
        batch_op.drop_column('month_double_time_rated')
        batch_op.drop_column('month_time_half_pay')
        batch_op.drop_column('month_time_half_rated')
        batch_op.drop_column('month_holiday_pay')
        batch_op.drop_column('month_holiday_rated')
        batch_op.drop_column('month_vja_pay')
        batch_op.drop_column('month_vja_rated')
        batch_op.drop_column('month_vacation_sick_pay')
        batch_op.drop_column('month_tfp_pay')
        batch_op.drop_column('month_int_tafb_pay')
        batch_op.drop_column('month_tafb_pay')

    # ### end Alembic commands ###
