"""message

Revision ID: 8c57516791a7
Revises: b05959b85e63
Create Date: 2023-09-12 01:17:45.275779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c57516791a7'
down_revision = 'b05959b85e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserve_no_fly_holiday', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reserve_no_fly_hours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days_table', schema=None) as batch_op:
        batch_op.drop_column('reserve_no_fly_hours')
        batch_op.drop_column('reserve_no_fly_holiday')

    # ### end Alembic commands ###
