"""message

Revision ID: b2b6dfb59398
Revises: bdc22e2892aa
Create Date: 2023-09-08 12:00:01.157387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b6dfb59398'
down_revision = 'bdc22e2892aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pairings_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tafb_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('int_tafb_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pairing_tfp_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pairing_vacation_sick_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pairing_vja_rated', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pairing_vja_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pairing_holiday_rated', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pairing_holiday_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pairing_time_half_rated', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pairing_time_half_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pairing_double_time_rated', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pairing_double_time_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pairing_double_half_rated', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pairing_double_half_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pairing_triple_rated', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pairing_triple_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pairing_overrides_pay', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pairing_a_pay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pairing_total_credits', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pairing_total_credits_rated', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pairing_total_pay', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pairings_table', schema=None) as batch_op:
        batch_op.drop_column('pairing_total_pay')
        batch_op.drop_column('pairing_total_credits_rated')
        batch_op.drop_column('pairing_total_credits')
        batch_op.drop_column('pairing_a_pay')
        batch_op.drop_column('pairing_overrides_pay')
        batch_op.drop_column('pairing_triple_pay')
        batch_op.drop_column('pairing_triple_rated')
        batch_op.drop_column('pairing_double_half_pay')
        batch_op.drop_column('pairing_double_half_rated')
        batch_op.drop_column('pairing_double_time_pay')
        batch_op.drop_column('pairing_double_time_rated')
        batch_op.drop_column('pairing_time_half_pay')
        batch_op.drop_column('pairing_time_half_rated')
        batch_op.drop_column('pairing_holiday_pay')
        batch_op.drop_column('pairing_holiday_rated')
        batch_op.drop_column('pairing_vja_pay')
        batch_op.drop_column('pairing_vja_rated')
        batch_op.drop_column('pairing_vacation_sick_pay')
        batch_op.drop_column('pairing_tfp_pay')
        batch_op.drop_column('int_tafb_pay')
        batch_op.drop_column('tafb_pay')

    # ### end Alembic commands ###
