"""message

Revision ID: cf219d1322ed
Revises: 
Create Date: 2023-09-07 15:47:28.160607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf219d1322ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('user_role', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('tfp_pay', sa.Float(), nullable=True),
    sa.Column('per_diem_pay', sa.Float(), nullable=True),
    sa.Column('international_per_diem_pay', sa.Float(), nullable=True),
    sa.Column('override_pay', sa.Float(), nullable=True),
    sa.Column('a_postion_pay', sa.Float(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_table'))
    )
    op.create_table('years_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('year_tfp', sa.Float(), nullable=True),
    sa.Column('year_vja', sa.Float(), nullable=True),
    sa.Column('year_holiday', sa.Float(), nullable=True),
    sa.Column('year_time_half', sa.Float(), nullable=True),
    sa.Column('year_double_time', sa.Float(), nullable=True),
    sa.Column('year_double_half', sa.Float(), nullable=True),
    sa.Column('year_triple', sa.Float(), nullable=True),
    sa.Column('year_overrides', sa.Integer(), nullable=True),
    sa.Column('year_a_hours', sa.Float(), nullable=True),
    sa.Column('year_tafb_total', sa.Float(), nullable=True),
    sa.Column('year_int_tafb_total', sa.Float(), nullable=True),
    sa.Column('year_duty_hours', sa.Float(), nullable=True),
    sa.Column('year_vacation_sick', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_years_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_years_table'))
    )
    op.create_table('months_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('guarantee_hours', sa.Float(), nullable=True),
    sa.Column('month_tfp', sa.Float(), nullable=True),
    sa.Column('month_vja', sa.Float(), nullable=True),
    sa.Column('month_holiday', sa.Float(), nullable=True),
    sa.Column('month_time_half', sa.Float(), nullable=True),
    sa.Column('month_double_time', sa.Float(), nullable=True),
    sa.Column('month_double_half', sa.Float(), nullable=True),
    sa.Column('month_triple', sa.Float(), nullable=True),
    sa.Column('month_overrides', sa.Integer(), nullable=True),
    sa.Column('month_a_hours', sa.Float(), nullable=True),
    sa.Column('month_tafb_total', sa.Float(), nullable=True),
    sa.Column('month_int_tafb_total', sa.Float(), nullable=True),
    sa.Column('month_duty_hours', sa.Float(), nullable=True),
    sa.Column('month_vacation_sick', sa.Float(), nullable=True),
    sa.Column('year_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['year_id'], ['years_table.id'], name=op.f('fk_months_table_year_id_years_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_months_table'))
    )
    op.create_table('pairings_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pairing_name', sa.String(), nullable=True),
    sa.Column('tafb_total', sa.Float(), nullable=True),
    sa.Column('int_tafb_total', sa.Float(), nullable=True),
    sa.Column('reserve_block', sa.Boolean(), nullable=True),
    sa.Column('pairing_tfp', sa.Float(), nullable=True),
    sa.Column('pairing_vja', sa.Float(), nullable=True),
    sa.Column('pairing_holiday', sa.Float(), nullable=True),
    sa.Column('pairing_time_half', sa.Float(), nullable=True),
    sa.Column('pairing_double_time', sa.Float(), nullable=True),
    sa.Column('pairing_double_half', sa.Float(), nullable=True),
    sa.Column('pairing_triple', sa.Float(), nullable=True),
    sa.Column('pairing_overrides', sa.Integer(), nullable=True),
    sa.Column('pairing_a_hours', sa.Float(), nullable=True),
    sa.Column('pairing_duty_hours', sa.Float(), nullable=True),
    sa.Column('pairing_vacation_sick', sa.Float(), nullable=True),
    sa.Column('month_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['month_id'], ['months_table.id'], name=op.f('fk_pairings_table_month_id_months_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pairings_table'))
    )
    op.create_table('days_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('total_tfp', sa.Float(), nullable=True),
    sa.Column('vacation_sick', sa.Float(), nullable=True),
    sa.Column('vacation_sick_pay', sa.Float(), nullable=True),
    sa.Column('vja', sa.Float(), nullable=True),
    sa.Column('vja_rated', sa.Float(), nullable=True),
    sa.Column('vja_pay', sa.Float(), nullable=True),
    sa.Column('holiday', sa.Float(), nullable=True),
    sa.Column('holiday_rated', sa.Float(), nullable=True),
    sa.Column('holiday_pay', sa.Float(), nullable=True),
    sa.Column('time_half', sa.Float(), nullable=True),
    sa.Column('time_half_rated', sa.Float(), nullable=True),
    sa.Column('time_half_pay', sa.Float(), nullable=True),
    sa.Column('double_time', sa.Float(), nullable=True),
    sa.Column('double_time_rated', sa.Float(), nullable=True),
    sa.Column('double_time_pay', sa.Float(), nullable=True),
    sa.Column('double_half', sa.Float(), nullable=True),
    sa.Column('double_half_rated', sa.Float(), nullable=True),
    sa.Column('double_half_pay', sa.Float(), nullable=True),
    sa.Column('triple', sa.Float(), nullable=True),
    sa.Column('triple_rated', sa.Float(), nullable=True),
    sa.Column('triple_pay', sa.Float(), nullable=True),
    sa.Column('overrides', sa.Integer(), nullable=True),
    sa.Column('overrides_pay', sa.Float(), nullable=True),
    sa.Column('a_position', sa.Boolean(), nullable=True),
    sa.Column('a_hours', sa.Float(), nullable=True),
    sa.Column('total_credits', sa.Float(), nullable=True),
    sa.Column('total_credits_rated', sa.Float(), nullable=True),
    sa.Column('total_pay', sa.Float(), nullable=True),
    sa.Column('reserve_no_fly', sa.Boolean(), nullable=True),
    sa.Column('daily_duty_hours', sa.Float(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('type_of_day', sa.String(), nullable=True),
    sa.Column('pairing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pairing_id'], ['pairings_table.id'], name=op.f('fk_days_table_pairing_id_pairings_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_days_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days_table')
    op.drop_table('pairings_table')
    op.drop_table('months_table')
    op.drop_table('years_table')
    op.drop_table('users_table')
    # ### end Alembic commands ###
