"""message

Revision ID: e860f7f36c7a
Revises: 4d4c17845eb1
Create Date: 2023-09-12 02:10:18.681367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e860f7f36c7a'
down_revision = '4d4c17845eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserve_no_fly_pay', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days_table', schema=None) as batch_op:
        batch_op.drop_column('reserve_no_fly_pay')

    # ### end Alembic commands ###
