"""message

Revision ID: fea6e15acd3b
Revises: 4e50c8af5bfc
Create Date: 2023-09-09 10:06:19.260921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea6e15acd3b'
down_revision = '4e50c8af5bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pairings_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pairing_guarantee_hours_worked_rated', sa.Float(), nullable=True))
        batch_op.drop_column('pairing_guarantee_hours_worked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pairings_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pairing_guarantee_hours_worked', sa.FLOAT(), nullable=True))
        batch_op.drop_column('pairing_guarantee_hours_worked_rated')

    # ### end Alembic commands ###
